### PR TITLE
#45 Pass url while creating  404 error message

### PR DESCRIPTION
**Pull request by bhargavigundaa**
Lets say I've received an 404 error in Universal router . And I'm trying to debug the Url that caused the error, I cant see the url as while creating the error we are not passing the URL

### CODE REVIEW

**Comment by sap9433** [comment]
So we have been using universal  router at production with https://github.com/kriasoft/react-starter-kit. In error page we are trying to log the error URL , but saw it's never being passed . With this change that issue is solved.

I tested it . can you kindly merge.

**Comment by bhargavigundaa** [comment]
1) Lets say user have reached this page - https://github.com/kriasoft/react-starter-kit/blob/master/src/routes/error/ErrorPage.js. He wont know which URL caused this .

2) A url call failed at server side and passed in client side  . Now user sees [error page](https://github.com/kriasoft/react-starter-kit/blob/master/src/routes/error/ErrorPage.js) coming from backend , and after a few mili-seconds client side rendered page shows up . Now users are complaining about this issue in prod and you dont know what's causing this . Solution is add following code at Line number 15 in the error above page. That does the server logging for you,  but it's not much of help , as it's not printing the URL.

**Comment by langpavel** [comment]
What about only pass copy of context object into Error instance?
Like
```js
  if (result === undefined && errorRoute) {
    const error = new Error('Not found');
    error.status = 404;
    error.context = { ...context };
    context.error = error;
    return await errorRoute.action(context, {});
  }
```

**Comment by sap9433** [comment]
not sure why it's backwork compatible and our solution wasn't.

all i know is ours was tested and live on one of india's largest ecommerce
store. And we are facing problem as its taking time to merge even the
simplest PR

**Comment by langpavel** [comment]
I think this error should tightly follow HTTP status codes. Additional info should not be part of message

**Comment by frenzzy** [comment]
This is out of date because `/error` route has been removed from the core in #48

**Pull request closed without merging**
