### PR TITLE
Router::generate(name string, params object) - generate paths by name

### PR DESCRIPTION
**Pull request by sanches89**
Implement Router::generate(name string, params object) to use in the Link component of React Starter Kit

### CODE REVIEW

**Comment by koistya** [comment]
I think supporting optional `name` parameter in each route is a great idea. But not sure if "generate URL" functionality should be a part of the core routing library. What do you think?

**Comment by koistya** [comment]
@sanchesic89 what do you think about this approach - PR #24.

**Comment by koistya** [comment]
@sanchesic89 FYI, I just have cleaned up the project, removed all the extra dependencies not related to the router itself. What do you think about having "generate URL" functionality in some external class/utility? For example, you can have a list of routes as a JavaScript array:

```js
// ./routes/index.js
export default [
  { id: 'home', path: '/', action: ... },
  { id: 'account:login', path: '/login': action: ... }
];
```

That can be used by both the router and a "link builder", for example:

```js
import Router from 'universal-router';
import routes from './routes';

const router = new Router(routes);
```

```js
// Link/URL builder
import routes from '../routes';

function createLink(routeID, params) { ... }

export default createLink();
```

That can be used as `createLink('product', { id: 123 })`.

**Comment by tommiv** [comment]
Any news on this, guys? It's highly required feature.

**Comment by langpavel** [comment]
@koistya Hi, I'm think this is especially useful and really often requested feature. Can you consider merge? I must admit that I didn't reviewed code carefully but I'm sure @sanches89 using this in production.

@sanches89 Can you give us feedback, do you using this in project?

**Comment by sanches89** [comment]
Hi everyone, the project change so much that I need to rebuild all the implementation. So I made a new pull request #74

**Comment by gustavohenke** [comment]
So close this one @sanches89 :)

**Pull request closed without merging**
