### PR TITLE
Remove errors handler from core

### PR DESCRIPTION
**Pull request by frenzzy**
To handle the 404, add such route to the end:
```js
const routes = [
  // your routes here
  { path: '*', action() { return 'Page not found' } }
]
```

To handle any other errors, use try catch:
```js
try {
  await UniversalRouter.resolve(routes, '/path')
} catch (error) {
  // handle an error
}
```

### CODE REVIEW

**Comment by koistya** [comment]
This will make the code that uses Universal Router more complex. Why would you want to do that?

**Comment by frenzzy** [comment]
1. To handle errors in different ways on the client and server-side
2. Hide hardcoded `/error` page from website
3. Use different routes/layouts for error and 404

**Comment by everdimension** [comment]
@frenzzy 
> To handle the 404, add such route to the end:

Can't you do the same right now if just don't set the `/error` route?

> Better performance: do not call heavy try catch statement for each route

But you're doing pretty much the same try catch in your example:

>    ```try {
          await UniversalRouter.resolve(routes, '/path')
        } catch (error) {
          // handle an error
        }```

**Comment by frenzzy** [comment]
> Can't you do the same right now if you just don't set the `/error` route?

Yes, we can.

> But you're doing pretty much the same try catch in your example:
>> ```js
>> try {
>>   await UniversalRouter.resolve(routes, '/path')
>> } catch (error) {
>>   // handle an error
>> }
>> ```

Yes, but not for each route separately.

One more example:
```js
UniversalRouter.resolve(routes, '/path')
  .then(component => render(component || <NotFoundPage />))
  .catch(error => render(<ErrorPage error={error} />))
```

**Pull request merged**
